stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: home-automation-front
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  DOCKER_IMAGE_TAGGED: ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_INGRESS_HOST: automation.home.maximemoreillon.com

image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

build:
  stage: build
  only:
    - master
  # tags:
  #   - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    # Building and tagging the container image
    - docker build -t ${DOCKER_IMAGE} .
    - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_TAGGED}
    # Pushing the image to the registry
    - docker push ${DOCKER_IMAGE}
    - docker push ${DOCKER_IMAGE_TAGGED}

deploy:
  stage: deploy
  only:
    - master
  # tags:
  #   - dind
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s_home/kubernetes-agent:home-talos
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
